### ISSUE TITLE
nptBurst.js: 15 in Promise: Illegal invocation

### ISSUE THREAD

**Issue by ghost** [nikolai3d/ntpsync#3]
Not working even if add that index.js manually.

**Comment by nikolai3d** [comment]
@Cherviakov Does this still manifest?

**Comment by rlueder** [comment]
Having the same issue on Chrome 65 (Mac OS):

TypeError: Illegal invocation
    at ntpBurstRequest.js:15
    at new Promise (<anonymous>)
    at delay (ntpBurstRequest.js:14)
    at Object.ntpDatePromiseBurstTimeout (ntpBurstRequest.js:134)
    at ntpSync.js:20
    at new Promise (<anonymous>)
    at Object.ntpLocalClockDeltaPromise (ntpSync.js:13)

![ntpsync_console_error](https://user-images.githubusercontent.com/341543/38213997-d536695a-3688-11e8-91aa-eab01656e419.gif)

Errors above are triggered when using the snippet from the Default Usage:

```
ntpsync.ntpLocalClockDeltaPromise().then((iNTPData) => {
    console.log(`(Local Time - NTP Time) Delta = ${iNTPData.minimalNTPLatencyDelta} ms`);
    console.log(`Minimal Ping Latency was ${iNTPData.minimalNTPLatency} ms`);
    console.log(`Total ${iNTPData.totalSampleCount} successful NTP Pings`);
}).catch((err) => {
    console.log(err);
});

**Comment by Connum** [comment]
Same problem here, running node 8.11.1 - has anyone ever gotten this to work?

**Comment by ghost** [comment]
It was so long ago so I have no idea what I was working on, and anyway there no much context. Closing.
